# Generated by Django 3.1.7 on 2021-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20210316_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='pockemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
