# Generated by Django 3.1.7 on 2021-03-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pockemonentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PockemonEntry',
            new_name='PokemonEntity',
        ),
    ]
