# Generated by Django 3.1.7 on 2021-03-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemonentity_appear_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='appear_at',
            new_name='appeared_at',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
