# Generated by Django 3.1.7 on 2021-03-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20210316_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pockemon',
            new_name='pokemon',
        ),
    ]
