# Generated by Django 3.1.7 on 2021-03-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='en_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='jp_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
