# Generated by Django 3.1.7 on 2021-03-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20210317_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='progenitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evalution', to='pokemon_entities.pokemon'),
        ),
    ]
